/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CompanyDashboardRouteImport } from './routes/company.dashboard'
import { Route as CompanyPostJobRouteImport } from './routes/company.post-job'
import { Route as StudentAnnouncementsRouteImport } from './routes/student.announcements'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentJobsRouteImport } from './routes/student.jobs'
import { Route as StudentMarksheetsRouteImport } from './routes/student.marksheets'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentResumeRouteImport } from './routes/student.resume'
import { Route as TpoAnnouncementsRouteImport } from './routes/tpo.announcements'
import { Route as TpoCompaniesRouteImport } from './routes/tpo.companies'
import { Route as TpoDashboardRouteImport } from './routes/tpo.dashboard'
import { Route as TpoSelectStudentsRouteImport } from './routes/tpo.select-students'
import { Route as TpoSettingsRouteImport } from './routes/tpo.settings'
import { Route as TpoStudentsRouteImport } from './routes/tpo.students'
import { Route as CompanyJobsIndexRouteImport } from './routes/company.jobs.index'
import { Route as CompanyJobsIdApplicantsRouteImport } from './routes/company.jobs.$id.applicants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/company/dashboard',
  path: '/company/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPostJobRoute = CompanyPostJobRouteImport.update({
  id: '/company/post-job',
  path: '/company/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAnnouncementsRoute = StudentAnnouncementsRouteImport.update({
  id: '/student/announcements',
  path: '/student/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/student/applications',
  path: '/student/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentJobsRoute = StudentJobsRouteImport.update({
  id: '/student/jobs',
  path: '/student/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMarksheetsRoute = StudentMarksheetsRouteImport.update({
  id: '/student/marksheets',
  path: '/student/marksheets',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResumeRoute = StudentResumeRouteImport.update({
  id: '/student/resume',
  path: '/student/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const TpoAnnouncementsRoute = TpoAnnouncementsRouteImport.update({
  id: '/tpo/announcements',
  path: '/tpo/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const TpoCompaniesRoute = TpoCompaniesRouteImport.update({
  id: '/tpo/companies',
  path: '/tpo/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const TpoDashboardRoute = TpoDashboardRouteImport.update({
  id: '/tpo/dashboard',
  path: '/tpo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TpoSelectStudentsRoute = TpoSelectStudentsRouteImport.update({
  id: '/tpo/select-students',
  path: '/tpo/select-students',
  getParentRoute: () => rootRouteImport,
} as any)
const TpoSettingsRoute = TpoSettingsRouteImport.update({
  id: '/tpo/settings',
  path: '/tpo/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TpoStudentsRoute = TpoStudentsRouteImport.update({
  id: '/tpo/students',
  path: '/tpo/students',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsIndexRoute = CompanyJobsIndexRouteImport.update({
  id: '/company/jobs/',
  path: '/company/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsIdApplicantsRoute = CompanyJobsIdApplicantsRouteImport.update({
  id: '/company/jobs/$id/applicants',
  path: '/company/jobs/$id/applicants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/post-job': typeof CompanyPostJobRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/jobs': typeof StudentJobsRoute
  '/student/marksheets': typeof StudentMarksheetsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resume': typeof StudentResumeRoute
  '/tpo/announcements': typeof TpoAnnouncementsRoute
  '/tpo/companies': typeof TpoCompaniesRoute
  '/tpo/dashboard': typeof TpoDashboardRoute
  '/tpo/select-students': typeof TpoSelectStudentsRoute
  '/tpo/settings': typeof TpoSettingsRoute
  '/tpo/students': typeof TpoStudentsRoute
  '/company/jobs/': typeof CompanyJobsIndexRoute
  '/company/jobs/$id/applicants': typeof CompanyJobsIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/post-job': typeof CompanyPostJobRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/jobs': typeof StudentJobsRoute
  '/student/marksheets': typeof StudentMarksheetsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resume': typeof StudentResumeRoute
  '/tpo/announcements': typeof TpoAnnouncementsRoute
  '/tpo/companies': typeof TpoCompaniesRoute
  '/tpo/dashboard': typeof TpoDashboardRoute
  '/tpo/select-students': typeof TpoSelectStudentsRoute
  '/tpo/settings': typeof TpoSettingsRoute
  '/tpo/students': typeof TpoStudentsRoute
  '/company/jobs': typeof CompanyJobsIndexRoute
  '/company/jobs/$id/applicants': typeof CompanyJobsIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/post-job': typeof CompanyPostJobRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/jobs': typeof StudentJobsRoute
  '/student/marksheets': typeof StudentMarksheetsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resume': typeof StudentResumeRoute
  '/tpo/announcements': typeof TpoAnnouncementsRoute
  '/tpo/companies': typeof TpoCompaniesRoute
  '/tpo/dashboard': typeof TpoDashboardRoute
  '/tpo/select-students': typeof TpoSelectStudentsRoute
  '/tpo/settings': typeof TpoSettingsRoute
  '/tpo/students': typeof TpoStudentsRoute
  '/company/jobs/': typeof CompanyJobsIndexRoute
  '/company/jobs/$id/applicants': typeof CompanyJobsIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/company/dashboard'
    | '/company/post-job'
    | '/student/announcements'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/jobs'
    | '/student/marksheets'
    | '/student/profile'
    | '/student/resume'
    | '/tpo/announcements'
    | '/tpo/companies'
    | '/tpo/dashboard'
    | '/tpo/select-students'
    | '/tpo/settings'
    | '/tpo/students'
    | '/company/jobs/'
    | '/company/jobs/$id/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/company/dashboard'
    | '/company/post-job'
    | '/student/announcements'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/jobs'
    | '/student/marksheets'
    | '/student/profile'
    | '/student/resume'
    | '/tpo/announcements'
    | '/tpo/companies'
    | '/tpo/dashboard'
    | '/tpo/select-students'
    | '/tpo/settings'
    | '/tpo/students'
    | '/company/jobs'
    | '/company/jobs/$id/applicants'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/company/dashboard'
    | '/company/post-job'
    | '/student/announcements'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/jobs'
    | '/student/marksheets'
    | '/student/profile'
    | '/student/resume'
    | '/tpo/announcements'
    | '/tpo/companies'
    | '/tpo/dashboard'
    | '/tpo/select-students'
    | '/tpo/settings'
    | '/tpo/students'
    | '/company/jobs/'
    | '/company/jobs/$id/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyPostJobRoute: typeof CompanyPostJobRoute
  StudentAnnouncementsRoute: typeof StudentAnnouncementsRoute
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentJobsRoute: typeof StudentJobsRoute
  StudentMarksheetsRoute: typeof StudentMarksheetsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResumeRoute: typeof StudentResumeRoute
  TpoAnnouncementsRoute: typeof TpoAnnouncementsRoute
  TpoCompaniesRoute: typeof TpoCompaniesRoute
  TpoDashboardRoute: typeof TpoDashboardRoute
  TpoSelectStudentsRoute: typeof TpoSelectStudentsRoute
  TpoSettingsRoute: typeof TpoSettingsRoute
  TpoStudentsRoute: typeof TpoStudentsRoute
  CompanyJobsIndexRoute: typeof CompanyJobsIndexRoute
  CompanyJobsIdApplicantsRoute: typeof CompanyJobsIdApplicantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/company/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/post-job': {
      id: '/company/post-job'
      path: '/company/post-job'
      fullPath: '/company/post-job'
      preLoaderRoute: typeof CompanyPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/announcements': {
      id: '/student/announcements'
      path: '/student/announcements'
      fullPath: '/student/announcements'
      preLoaderRoute: typeof StudentAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/jobs': {
      id: '/student/jobs'
      path: '/student/jobs'
      fullPath: '/student/jobs'
      preLoaderRoute: typeof StudentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/marksheets': {
      id: '/student/marksheets'
      path: '/student/marksheets'
      fullPath: '/student/marksheets'
      preLoaderRoute: typeof StudentMarksheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/resume': {
      id: '/student/resume'
      path: '/student/resume'
      fullPath: '/student/resume'
      preLoaderRoute: typeof StudentResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpo/announcements': {
      id: '/tpo/announcements'
      path: '/tpo/announcements'
      fullPath: '/tpo/announcements'
      preLoaderRoute: typeof TpoAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpo/companies': {
      id: '/tpo/companies'
      path: '/tpo/companies'
      fullPath: '/tpo/companies'
      preLoaderRoute: typeof TpoCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpo/dashboard': {
      id: '/tpo/dashboard'
      path: '/tpo/dashboard'
      fullPath: '/tpo/dashboard'
      preLoaderRoute: typeof TpoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpo/select-students': {
      id: '/tpo/select-students'
      path: '/tpo/select-students'
      fullPath: '/tpo/select-students'
      preLoaderRoute: typeof TpoSelectStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpo/settings': {
      id: '/tpo/settings'
      path: '/tpo/settings'
      fullPath: '/tpo/settings'
      preLoaderRoute: typeof TpoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpo/students': {
      id: '/tpo/students'
      path: '/tpo/students'
      fullPath: '/tpo/students'
      preLoaderRoute: typeof TpoStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs/': {
      id: '/company/jobs/'
      path: '/company/jobs'
      fullPath: '/company/jobs/'
      preLoaderRoute: typeof CompanyJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs/$id/applicants': {
      id: '/company/jobs/$id/applicants'
      path: '/company/jobs/$id/applicants'
      fullPath: '/company/jobs/$id/applicants'
      preLoaderRoute: typeof CompanyJobsIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyPostJobRoute: CompanyPostJobRoute,
  StudentAnnouncementsRoute: StudentAnnouncementsRoute,
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentJobsRoute: StudentJobsRoute,
  StudentMarksheetsRoute: StudentMarksheetsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResumeRoute: StudentResumeRoute,
  TpoAnnouncementsRoute: TpoAnnouncementsRoute,
  TpoCompaniesRoute: TpoCompaniesRoute,
  TpoDashboardRoute: TpoDashboardRoute,
  TpoSelectStudentsRoute: TpoSelectStudentsRoute,
  TpoSettingsRoute: TpoSettingsRoute,
  TpoStudentsRoute: TpoStudentsRoute,
  CompanyJobsIndexRoute: CompanyJobsIndexRoute,
  CompanyJobsIdApplicantsRoute: CompanyJobsIdApplicantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
